version: "3.9"
services:
  db:
    build: ./db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5444:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  app:
    build: ./app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASS: mypass
      DB_NAME: mydb
    command: python app.py
